[package]
name = "vel"
version = "0.0.1"
authors = ["Yusuke Matsushita"]
description = "Vel's language engine"
repository = "https://github.com/hopv/vel"
license = "MIT"
edition = "2021"
publish = false

[dependencies]
bumpalo = "3.11.1"
